input.onButtonPressed(Button.A, function () {
    music.ringTone(262)
    soundExpression.giggle.playUntilDone()
    basic.showString("SRINIKETH")
})
input.onButtonPressed(Button.B, function () {
    music.ringTone(262)
    soundExpression.giggle.playUntilDone()
    basic.showString("PANEENDRA")
})
basic.showString("SRINIKETH")
music.startMelody(music.builtInMelody(Melodies.Dadadadum), MelodyOptions.Once)
music.startMelody(music.builtInMelody(Melodies.Birthday), MelodyOptions.Forever)
input.calibrateCompass()
led.setDisplayMode(DisplayMode.BlackAndWhite)
basic.showArrow(ArrowNames.North)
basic.showArrow(ArrowNames.NorthEast)
basic.showArrow(ArrowNames.East)
basic.showArrow(ArrowNames.SouthEast)
basic.showArrow(ArrowNames.South)
basic.showArrow(ArrowNames.SouthWest)
basic.showArrow(ArrowNames.West)
basic.showArrow(ArrowNames.NorthWest)
basic.showIcon(IconNames.Heart)
basic.showIcon(IconNames.Skull)
basic.showIcon(IconNames.Ghost)
basic.showIcon(IconNames.Square)
basic.showIcon(IconNames.SmallSquare)
basic.showIcon(IconNames.SmallDiamond)
basic.showIcon(IconNames.Square)
basic.showIcon(IconNames.SmallSquare)
basic.showIcon(IconNames.SmallDiamond)
